apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: {name: warmimages.mattmoor.io}
spec:
  group: mattmoor.io
  names: {kind: WarmImage, plural: warmimages, singular: warmimage}
  scope: Cluster
  version: v1

---
apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: warmimage-controller}
spec:
  replicas: 1
  template:
    metadata:
      labels: {app: warmimage-controller}
    spec:
      containers:
      - env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef: {fieldPath: metadata.namespace}
        - {name: OWNER_NAME, value: warmimage-controller}
        image: gcr.io/mattmoor-public/warm-image/controller@sha256:b2d58f4adbad6feb81cb80d7fe42ad6d30611c94ad659be0fb3e0aa9bf5a66ec
        name: warmimage-controller

