apiVersion: v1
kind: Namespace
metadata: {name: warmimage-system}

---
apiVersion: v1
kind: ServiceAccount
metadata: {name: warmimage-controller, namespace: warmimage-system}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata: {name: warmimage-controller-admin}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: cluster-admin}
subjects:
- {kind: ServiceAccount, name: warmimage-controller, namespace: warmimage-system}

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: {name: warmimages.mattmoor.io}
spec:
  group: mattmoor.io
  names: {kind: WarmImage, plural: warmimages, singular: warmimage}
  scope: Namespaced
  version: v2

---
apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: warmimage-controller, namespace: warmimage-system}
spec:
  replicas: 1
  template:
    metadata:
      labels: {app: warmimage-controller}
    spec:
      containers:
      - args: [-logtostderr=true, -stderrthreshold=INFO, -sleeper, 'gcr.io/mattmoor-public/sleeper@sha256:d431f1c78bb16fbb0c9831a610bc9580379a4f9ab0a339efd2ffb36ea5ffeca2']
        image: gcr.io/mattmoor-public/warmimage-controller@sha256:ead3ea8b6acb6f936d2a9f11e25d3f596db9d4824b344e69d4248109dceec2fb
        name: warmimage-controller
      serviceAccountName: warmimage-controller

