apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: warmimage-controller
  namespace: warmimage-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: warmimage-controller
    spec:
      serviceAccountName: warmimage-controller
      containers:
      - name: warmimage-controller
        image: github.com/mattmoor/warm-image/cmd/controller
        args:
        - "-logtostderr=true"
        - "-stderrthreshold=INFO"
        - "-sleeper"
        - "github.com/mattmoor/warm-image/cmd/sleeper"
